### ISSUE TITLE
Problem with the order of the parameters

### ISSUE THREAD

**Issue by fasouto** [rmax/dirbot-mysql#1]
I was trying the MySQL pipeline and It wasn't working for me.
In the process_item you pass as first parameter the item and second the spider, and scrapy(at least 0.14) expect : item, spider.
http://doc.scrapy.org/en/0.14/topics/item-pipeline.html#process_item
    def process_item(self, item, spider):
instead of
    def process_item(self, spider, item):

Anyway, thanks for share this code.

**Comment by rmax** [comment]
Sorry for the delayed response. You are right, this code was from 0.11-0.12 days in the versions the signature of the process_item has changed.

**Comment by fasouto** [comment]
I just found this in my issues tab 4 years later :smile: , closing
